export {default as Blog } from './Blog/Blog'
export {default as Footer } from './Footer'
export { default as FooterSlider } from './FooterSlider'
export { default as UpcomingEvents } from './UpcomingEvents'
export { default as Achievements } from './Achievements'